# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/radim/dev/ncurses/clock

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/radim/dev/ncurses/clock

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/radim/dev/ncurses/clock/CMakeFiles /Users/radim/dev/ncurses/clock//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/radim/dev/ncurses/clock/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named asciiclock

# Build rule for target.
asciiclock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asciiclock
.PHONY : asciiclock

# fast build rule for target.
asciiclock/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/build
.PHONY : asciiclock/fast

src/clock.o: src/clock.cpp.o
.PHONY : src/clock.o

# target to build an object file
src/clock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/clock.cpp.o
.PHONY : src/clock.cpp.o

src/clock.i: src/clock.cpp.i
.PHONY : src/clock.i

# target to preprocess a source file
src/clock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/clock.cpp.i
.PHONY : src/clock.cpp.i

src/clock.s: src/clock.cpp.s
.PHONY : src/clock.s

# target to generate assembly for a file
src/clock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/clock.cpp.s
.PHONY : src/clock.cpp.s

src/input.o: src/input.cpp.o
.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/interface.o: src/interface.cpp.o
.PHONY : src/interface.o

# target to build an object file
src/interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/interface.cpp.o
.PHONY : src/interface.cpp.o

src/interface.i: src/interface.cpp.i
.PHONY : src/interface.i

# target to preprocess a source file
src/interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/interface.cpp.i
.PHONY : src/interface.cpp.i

src/interface.s: src/interface.cpp.s
.PHONY : src/interface.s

# target to generate assembly for a file
src/interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/interface.cpp.s
.PHONY : src/interface.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/renderer.o: src/renderer.cpp.o
.PHONY : src/renderer.o

# target to build an object file
src/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/renderer.cpp.o
.PHONY : src/renderer.cpp.o

src/renderer.i: src/renderer.cpp.i
.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/renderer.cpp.i
.PHONY : src/renderer.cpp.i

src/renderer.s: src/renderer.cpp.s
.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/renderer.cpp.s
.PHONY : src/renderer.cpp.s

src/shapes.o: src/shapes.cpp.o
.PHONY : src/shapes.o

# target to build an object file
src/shapes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/shapes.cpp.o
.PHONY : src/shapes.cpp.o

src/shapes.i: src/shapes.cpp.i
.PHONY : src/shapes.i

# target to preprocess a source file
src/shapes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/shapes.cpp.i
.PHONY : src/shapes.cpp.i

src/shapes.s: src/shapes.cpp.s
.PHONY : src/shapes.s

# target to generate assembly for a file
src/shapes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/shapes.cpp.s
.PHONY : src/shapes.cpp.s

src/surface.o: src/surface.cpp.o
.PHONY : src/surface.o

# target to build an object file
src/surface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/surface.cpp.o
.PHONY : src/surface.cpp.o

src/surface.i: src/surface.cpp.i
.PHONY : src/surface.i

# target to preprocess a source file
src/surface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/surface.cpp.i
.PHONY : src/surface.cpp.i

src/surface.s: src/surface.cpp.s
.PHONY : src/surface.s

# target to generate assembly for a file
src/surface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciiclock.dir/build.make CMakeFiles/asciiclock.dir/src/surface.cpp.s
.PHONY : src/surface.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... asciiclock"
	@echo "... src/clock.o"
	@echo "... src/clock.i"
	@echo "... src/clock.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/interface.o"
	@echo "... src/interface.i"
	@echo "... src/interface.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/shapes.o"
	@echo "... src/shapes.i"
	@echo "... src/shapes.s"
	@echo "... src/surface.o"
	@echo "... src/surface.i"
	@echo "... src/surface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

